### ISSUE TITLE
Posts - Inbound federation

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#190]
Handle Inbox activities related to Notes. This should cover Create, Update, and Delete activities. There may be others in the future, but this is enough to provide meaningful federation for now.

- [x] Add handling in the Inbox controller for Create, Update, and Delete activities
- [x] Map the objects carried by those activities to Posts[^1]
- [x] Pass off those Posts to the PostService for handling

[^1]: I don't think these mappers exist yet. Please reach out with any question at all.

**Comment by gianlucaschoefer** [comment]
_Hi, first of all as this is my first comment I'd like to say that I really appreciate this project, its goals and how it is managed. 👍_

I had a look through the source code, architecture and ActivityPub specification, so I am considering a contribution. Let me know if you recommend starting with something else, but this issue seems like a good start. I'd like to ask some clarifying questions before offering a contribution though:

- I assume you mean `ActorController` when saying 'Inbox Controller'?
- Currently `IAuthzPostService` requires a profileId. In case of inbound activities no (local) profile exists, so I cannot see a sensible value here. Would the scope of this issue include offering a non-authzd access to the `Receive...` methods?
- My naive approach for the mappers would have been to map `ASActivity` to a `Post`. As an example, to populate `Post.Creators` I need to identify whether the `ASActivity.Actors` is a link or a value (object). Do I need to request the [actor's property information](https://www.w3.org/TR/activitypub/#actor-objects) from its server or is it enough to simply store their ID and the inbox URL will be identified only once it is required? It could be that I am misunderstanding the spec here, so please point me in the right direction.

**Comment by jenniferplusplus** [comment]
Thanks for reaching out! All good questions.

> I assume you mean ActorController when saying 'Inbox Controller'?

Yes, I meant the `ActorController`, sorry.

As a general note, I've been doing a lot of work in the ActorController recently. It's still in PR, because I try to leave a day or two for people to review changes before I merge them. You should have a look before you start working on code #293

> In case of inbound activities no (local) profile exists, so I cannot see a sensible value here.

Letterbook will create and manage profiles to represent remote actors. So, when we receive (for instance) a `Create:Note` activity, we would handle that by creating a new Post with a Note content. We would also create the profile for that remote actor, if it doesn't exist.

The authorization system will create a claims identity for inbound AP requests. The controller should only need to pass those claims to the profile service, ex.: `_profiles.As(User.Claims).CreatePost(...)`

In the event we don't already have a local representation for the actor, we'll need to create that before we can attribute posts to it. That's probably complicated to do, because in that case we likely want to push the whole task into the worker queue and handle it out of band so that we can give a timely response to the active HTTP request. I would not mind at all if you put off handling for that case until later.

> My naive approach for the mappers would have been to map ASActivity to a Post

There might already be mappers for `AS#Note` -> `Post`, but I could be wrong. I haven't been in that part of the code base in a little while. We don't really have consistent representations for Activities. We're more concerned with the Objects those activities are about. the overall idea is to use the activity to determine which actions we're taking (create, update, etc), and then map the `AS#Object` it contains to a Letterbook domain object. But generally, yes, you're on the right track.

> Do I need to request the [actor's property information](https://www.w3.org/TR/activitypub/#actor-objects) from its server

Yes. I need to do a little bit of cleanup in this area, but if you're trying to locate a profile via the ID Url (`FediId`, in letterbook terms), you can use the [`ResolveProfile(url)`](https://github.com/Letterbook/Letterbook/blob/3248f06f8578a06c5b7bd0b9d6ee3f35d51dbc1e/Letterbook.Core/ProfileService.cs#L542) method in the `ProfileService`. That will handle doing database lookups, and then falling back to network lookups if we don't have a (fresh) db record.

**Comment by jenniferplusplus** [comment]
@gianlucaschoefer I'm going to start working on post federation soon. Before I do, I want to check in and see if you ever made any progress.

**Comment by gianlucaschoefer** [comment]
@jenniferplusplus sorry for disappearing. Also, thank you for the detailed response to my questions. I already understand the project better because of it. 

> work on this

I actually did, and I think I have something basic, that is just missing a little bit of clean up and tests. I haven't gotten around to working on it since, but should be able to push something towards the end of the week. If I am at all blocking you here, please feel free to take this over. :)

**Comment by jenniferplusplus** [comment]
No worries, I've gotten side tracked into other things. I'll likely want to get back to code over the weekend, but there's plenty of other areas I can make progress.

Btw, we have a small discord for contributors. I try to keep substantial decision making on Github, where it's publicly visible. But chat is a better medium for getting help. If you'd like an invite, let me know where I can send it.
