### ISSUE TITLE
Add Razor front-end harness

### ISSUE THREAD

**Issue by mattly** [Letterbook/Letterbook#196]
## What is the goal of this feature?

Setup the necessary foundation for front-end work

## Describe the solution you'd like

Per discussion on Discord some months back, we need a Blazor harness setup in the app to enable front-end work. Sam had mentioned they were leaning towards the Blazor Server model.

### Describe alternatives you've considered

We talked about a bunch of alternatives, mostly JS-centric single-page app models such as React, Vue, or Svelte, and don't believe those make sense. Blazor fits into the .NET world.

### Additional context

If you can get me to a "Hello World" page, I can start poking around from there. Given that #167 and authentication is still in the works, perhaps we can identify some good starting front-end features that don't require authentication, such as displaying a local timeline.

**Comment by jenniferplusplus** [comment]
Timelines are definitely not going to work at this stage. But I think the post form, and single post and thread views would be fully functional. We don't have real authorization yet, but I think we can add that later.

We could also support account creation and (soon) profile views and profile management.

**Comment by jenniferplusplus** [comment]
Actually, let me back up. We don't have the rest api for profiles, but all the lower level stuff exists already. That should be all that's needed to power razor/Blazor pages. Again, assuming we ignore auth for now

**Comment by jenniferplusplus** [comment]
Following up from some further discussion recently, Razor pages are likely a better fit for the project. At least right now. Notably, it's more of a conventional web server dynamic, which is likely to be more approachable to a bigger audience of contributors.

Also, in my view:
1. Blazor requires active sessions, which is hard to manage and scale
2. Blazor requires open server connections for server rendering, which is more intensive to scale
3. And I worry about the impact of network latency in production due to 1 and 2.

That said, I will plan to take this up next, and get an initial Razor pages front set up in the next few days.
